OpenConext/Stepup-SelfService

composer.json, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Security/Firewall/SamlListener.php
https://www.pivotaltracker.com/story/show/86891136
=> Ensure InResponseTo between request and response matches

app/config/config.yml, app/config/routing_dev.yml, composer.json, composer.lock
=> User friendly error pages

app/Resources/SurfnetStepupBundle/views/Exception/error.html.twig, app/Resources/SurfnetStepupBundle/views/Exception/error404.html.twig, app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, composer.lock
Routes and translations are application-specific.
=> Add templates for user-friendly error page.

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/Resources/translations/validators.en_GB.xliff, app/Resources/translations/validators.nl_NL.xliff, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/SmsController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/YubikeyController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/translations.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/YubikeySecondFactor/ProofOfPossessionResult.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/YubikeySecondFactorService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/YubikeyService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/YubikeyVerificationResult.php
=> More informative second factor error messages in case of user error

src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/RevokeSecondFactorType.php
https://www.pivotaltracker.com/story/show/85899128
=> Add cancel revocation button to revocation view

src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/registrationEmailSent.html.twig
https://www.pivotaltracker.com/story/show/86103344
=> Made table with registration code smaller

composer.json, composer.lock
Required for two things:
- Being able to set the subject on Saml Requests
- Update the metadata signing algorithm to SHA256
=> Updated saml2 and saml-bundle

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/Resources/translations/validators.en_GB.xliff, app/Resources/translations/validators.nl_NL.xliff, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Sms/provePossession.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Sms/sendChallenge.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Yubikey/provePossession.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/displaySecondFactorTypes.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/translations.twig
=> Modify translations

src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/displaySecondFactorTypes.html.twig
See https://www.pivotaltracker.com/story/show/85899418
=> Reorder the Second Factors

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/config/config.yml, app/config/parameters.yml.dist, app/config/samlstepupproviders_parameters.yml.dist
These were missing when the change was made to put the loa definition inside the SurfnetStepupBundle
=> Add loa definitions to configuration

composer.json, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Command/SendSmsChallengeCommand.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/SmsController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/SendSmsChallengeType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/public/less/style.less, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Sms/sendChallenge.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/revoke.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SmsSecondFactorService.php
Depends on https://github.com/SURFnet/Stepup-bundle/pull/12
Depends on https://github.com/SURFnet/Stepup-Middleware/pull/58
=> Consistent display of phonenumber

composer.json, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/YubikeySecondFactorService.php
=> Supply numeric Yubikey public IDs to the middleware

app/Resources/translations/messages.nl_NL.xliff, app/config/parameters.yml.dist, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/displaySecondFactorTypes.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/partial/secondFactor.html.twig
https://www.pivotaltracker.com/projects/1163646/stories/113748599
@rjkip can you review?
=> Make Tiqr app descriptions into links

src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/SendSmsChallengeType.php
=> Line out form element and button for SMS send-challenge

src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/VerifySmsChallengeType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Sms/provePossession.html.twig
https://www.pivotaltracker.com/n/projects/1163646/stories/100299518 punt 4
=> Format SMS posession proving form

src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RaService.php
This should also be tested more extensively and can be done in conjunction with Middleware's changes regarding this option.
=> Show RAA contact information if it has been configured, otherwise not

app/Resources/translations/validators.nl_NL.xliff, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Sms/sendChallenge.html.twig
HTML5 validation doesn't respect the application language selection.
=> Remove HTML5 validation in favor of server side validation.

.gitignore, app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/Resources/views/base.html.twig, app/config/config.yml, app/config/global_view_parameters.yml.dist, composer.json, src/Surfnet/StepupSelfService/SelfServiceBundle/Assert.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Exception/AssertionFailedException.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/GlobalViewParameters.php
[131975453](https://www.pivotaltracker.com/story/show/131975453)
This adds global view parameters, allowing multi-locale parameters to be injected in the view.
A multi-locale support URL is configured in this PR.
SURFnet/Stepup-RA#128
=> SelfService: Multi locale urls

composer.json, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/displaySecondFactorTypes.html.twig
[119815553](https://www.pivotaltracker.com/story/show/119815553)
OpenConext/Stepup-Middleware-clientbundle#49 and OpenConext/Stepup-Middleware#179 should be reviewed and merged first.
=> Apply Allowed Second Factors in SS

src/Surfnet/StepupSelfService/SelfServiceBundle/Service/U2fService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/YubikeyService.php
[126126187](https://www.pivotaltracker.com/story/show/126126187)
This correctly implements Guzzle 6 interfaces and uses the shared JsonHelper from the StepupBundle.
=> Correctly implement Guzzle 6 interfaces

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff
Per https://www.pivotaltracker.com/story/show/79436876
=> Update messages shown after testing token

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig
https://www.pivotaltracker.com/story/show/155351990
=> Layout and text updates of token overview screen

src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/displaySecondFactorTypes.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Value/AvailableTokenCollectionTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Value/AvailableTokenCollection.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Value/AvailableTokenInterface.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Value/BuiltInToken.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Value/GsspToken.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Value/HardcodedToken.php
The sort order of the available tokens was changed. To achieve this  goal, a collection object was added to the project collecting the GSSP and hard coded tokens.
Story details can be found in Pivotal
https://www.pivotaltracker.com/story/show/156311244
=> Improve token selection ordering

app/config/config.yml, app/config/config_dev.yml, app/config/parameters.yml.dist, composer.json, composer.lock
Based on Pieters work in the dev-vm branch, but added some additional commits.
=> Change dev logging configuration to use syslog instead of graylog

app/config/config.yml, app/config/parameters.yml.dist, composer.json, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SecondFactorController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/DependencyInjection/Configuration.php, src/Surfnet/StepupSelfService/SelfServiceBundle/DependencyInjection/SurfnetStepupSelfServiceSelfServiceExtension.php
**Review notes**
* See the commit messages for more details
**Todo**
=> Read number of tokens per institution from Middleware API

app/config/config_test.yml, app/config/services_test.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SmsSecondFactorService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SmsSecondFactorServiceInterface.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/TestDouble/Service/SmsSecondFactorService.php
See: https://www.pivotaltracker.com/story/show/160318902 for details
=> Provide behat support

CHANGELOG.md, app/config/config_test.yml, app/config/services_test.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/TestDouble/Factory/GuzzleApiFactory.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Value/BuiltInToken.php
In order to run behat tests successfully between different dev environments, some updates where in order. Please view individual commits for more details.
See: https://www.pivotaltracker.com/story/show/160318902
=> Test environment adjustments

app/Resources/views/base.html.twig
The help link in the footer should op en in a new tab.
=> Open help in new tab

app/config/parameters.yml.dist, app/config/security.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/security.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Security/Authentication/Handler/LogoutSuccessHandler.php
The logout redirect utrl didn't work. This commit will make sure the
redirect uri will work and adds multilingual support.
=> Introduce multi-lingual logout redirect

.travis.yml, CHANGELOG.md, composer.json, composer.json.travis, composer.lock, composer.lock.travis, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/EntryPointController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SecondFactorController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/IdentityService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SecondFactorService.php
All of the FGA logic resided on a feature branch in order to finish StepUp release 16 without interfering with the FGA development.
Now that release 16 is in a mature state, we can merge the FGA changes back to develop.
=> Merge the FGA feature branch back to develop

CHANGELOG.md, composer.lock
Symfony was upgraded to 3.4.26
Twig was upgraded to 1.39.1
=> Install security upgrades for release 17

composer.json, composer.lock, src/Surfnet/StepupSelfService/SamlStepupProviderBundle/DependencyInjection/Compiler/ViewConfigCollectionPass.php
Install recent Symfony security updates
Also pins twig/twig to a compatible version for use with the Mopa Bootstrap bundle.
=> Install various security updates

app/config/config_dev.yml, app/config/remote_vetting.yml, app/config/services_dev.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RemoteVettingController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/ApplicationHelper.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/AttributeMapper.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Configuration/RemoteVettingConfiguration.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Dto/AttributeListDto.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Encryption/IdentityData.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Encryption/IdentityEncrypter.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Encryption/IdentityEncrypterInterface.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeCollectionAggregate.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeCollectionInterface.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeMatch.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeMatchCollection.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVettingService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Dto/AttributeListDtoTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Encryption/FakeIdentityEncrypter.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Encryption/IdentityEncrypterIntegrationTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Encryption/IdentityEncrypterTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Value/AttributeCollectionInterfaceIntegrationTest.php
Summary of work done: 
1. The attributes have been aggregated
2. The other metedata stored alongside the attributes is collected and set on a identity data VO
3. Tied together these new concepts
4. Tried to add relevant tests
Read commit messages for details.
=> Finalize identity data encryption logic

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/Resources/translations/validators.en_GB.xliff, app/Resources/translations/validators.nl_NL.xliff, app/config/remote_vetting.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RemoteVettingController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/routing.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/displayVettingTypes.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/RemoteVetting/remoteVet.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig
During development two screens were added to choose between
the different vetting types. Those could be merged together.
=> Merge the (RA/RV) vetting screens

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/Resources/translations/validators.en_GB.xliff, app/Resources/translations/validators.nl_NL.xliff, src/Surfnet/StepupSelfService/SelfServiceBundle/Command/RemoteVetValidationCommand.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RemoteVettingController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Exception/InvalidRemoteVettingMappingException.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/RemoteVetAssertionMatchType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/RemoteVetValidationType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Form/fields.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/RemoteVetting/validation.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/AttributeMapper.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeMatch.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeMatchCollection.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVettingService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Mock/RemoteVetting/MockRemoteVetControllerTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/AttributeMapperTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Value/AttributeCollectionInterfaceIntegrationTest.php
In order match the attributes we needed to also display the local
values. Therefore a table was added. Also the label styling was
optimized so all information would be displayed more clearly.
https://www.pivotaltracker.com/n/projects/1163646/stories/171835180
=> Show more attribute information in matching form

app/config/remote_vetting.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RemoteVettingController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/routing.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/displayVettingTypes.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Dto/RemoteVettingIdenityProviderDto.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/IdentityProviderFactory.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/RemoteVettingContext.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/SamlCalloutHelper.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVettingService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SecondFactorService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Mock/RemoteVetting/MockRemoteVetControllerTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/RemoteVettingContextTest.php
Remove the remote vetting development efforts before releasing an MVP.
https://www.pivotaltracker.com/story/show/171571539
=> Remove remote veting development efforts

.travis.yml
In preparation for upgrading to PHP7.4 this will run test on the target
architecture.
=> Check for PHP7.4 compatibility

src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RemoteVettingController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/RemoteVettingContext.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVettingService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVettingServiceTestTest.php
Add some additional information to the RV logging in order to add
more valuable data to the RV pilot in case of potential regressions.
=> Add rv context data to logging

package.json, yarn.lock
=> Upgrade ansi-regex

composer.lock, translations/messages.en_GB.xliff, translations/messages.nl_NL.xliff, translations/validators.en_GB.xliff, translations/validators.nl_NL.xliff
Appropriate translation for when OpenConext/Stepup-bundle#65 is merged
=> Update translations, set translation for missing required attributes

composer.json, composer.lock, symfony.lock
And remember; composer require === require && update hence the numerous
ammount of composer updates installed. Which is kind of a good thing!
=> Install Monitor bundle 3.1.0

src/Surfnet/StepupSelfService/SelfServiceBundle/Command/VerifySmsChallengeCommand.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Command/VerifySmsRecoveryTokenChallengeCommand.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SelfAssertedTokensController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/AnchorType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/translations.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfAssertedTokens/RecoveryTokenService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfAssertedTokens/SafeStoreService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfAssertedTokens/SafeStoreState.php, translations/messages.en_GB.xliff, translations/messages.nl_NL.xliff, translations/validators.en_GB.xliff, translations/validators.nl_NL.xliff
A collection of improvements that align the first setup with the requirements set for the self-service application.
=> Recovery token finetuneing

composer.json, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Security/Authentication/SamlInteractionProvider.php, symfony.lock
In the process, also upgrade usages of the SAML2 libraries classes that changed their signature.
See: https://www.pivotaltracker.com/story/show/184071674
=> Upgrade Stepup SAML bundle

src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/VerifySmsChallengeType.php
This allows the (mobile) browser to help autofill
=> Make sms form autocomplete="one-time-code"

templates/base.html.twig
The wrong array was read during flash rendering.
=> Fix flash messages

.github/workflows/build-push-docker-image.yml, .github/workflows/tag-release.yml
Release actions have been replace with one action that can do all seperate actions. 
The build and push docker action has been updated to remove deprecations.
=> Replace release actions

templates/pdf.html.twig
The PDF message with details on where to vet the token had a broken image
=> Fix broken image in PDF

ci/qa/phpstan-baseline.php, composer.lock, config/openconext/parameters.yaml.dist, config/packages/framework.yaml, config/services.yaml, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SamlController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/EventListener/AuthenticatedUserListener.php, src/Surfnet/StepupSelfService/SelfServiceBundle/EventListener/ExplicitSessionTimeoutListener.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Security/Authentication/AuthenticatedSessionStateHandler.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Security/Authentication/Session/SessionLifetimeGuard.php
This add listeners to the chain to detect and set cookie settings. Cherrypicked #323 so that one can be deleted.
=> Programatically ensure cookie expiration

composer.json, composer.lock, config/routes.yaml, config/routes/controllers.yaml
=> Update latest dependencies
