src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/YubikeyController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Yubikey/provePossession.html.twig
> The Internet I scoured
> But my face has soured
> 'T is nix
> This solution, this fix
Alas, I used separate form calls to render the OTP field empty.
=> Always display empty Yubikey OTP field

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SmsService.php
See https://www.pivotaltracker.com/story/show/86103092
The email parameter was already available in both the [registration code sent][1] and [email verification email sent][2] pages
[1]: https://github.com/SURFnet/Stepup-SelfService/blob/5c7562b911bec9af43df03442365b016000ec7d0/src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/registrationEmailSent.html.twig#L14
[2]: https://github.com/SURFnet/Stepup-SelfService/blob/5c7562b911bec9af43df03442365b016000ec7d0/src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/emailVerificationEmailSent.html.twig#L14
=> Show email address in the email sent pages

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Saml/Exception/authnFailed.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Saml/Exception/preconditionNotMet.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Security/Firewall/SamlListener.php
- AuthnFailed - IdP failed to authenticate user
- * - All other cases where preconditions weren't met
The reason the response is rendered and set from the SamlListener and
not from a kernel listener is the fact that the firewall errors out
when the listener doesn't set a token.
=> Render informative error screens in case of the below resp. statuses.

src/Surfnet/StepupSelfService/SamlStepupProviderBundle/DependencyInjection/SurfnetStepupSelfServiceSamlStepupProviderExtension.php
the factory definition used was broken for some reason this was never caught in dev or test. Might have to do something with the 300+ commits between SF 2.6.4 and 2.6.6....
=> Fix issue where tiqr registration could not start

composer.json, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/IdentityService.php
depends on https://github.com/SURFnet/Stepup-Middleware-clientbundle/pull/32
depends on https://github.com/SURFnet/Stepup-Middleware/pull/94
=> Use new version of UpdateIdentityCommand

src/Surfnet/StepupSelfService/SelfServiceBundle/EventListener/LocaleListener.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Security/Authentication/Handler/ExplicitSessionTimeoutHandler.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/LocaleProviderService.php
[113611545](https://www.pivotaltracker.com/story/show/113611545)
This implements the locale cookie listener from the StepupBundle into SelfService.
For its RA counter-part, see: [Stepup-RA #123](https://github.com/SURFnet/Stepup-RA/pull/123).
=> Implement locale cookie listener from StepupBundle into SelfService

composer.lock
[135780169](https://www.pivotaltracker.com/story/show/135780169)
For an overview of changes between the current and the new SAML2 versions, see the [diff on Github](https://github.com/simplesamlphp/saml2/compare/v1.9...v1.10.3). This includes a security fix and the way SAML2 deals with EPTIs. The latter does not affect SelfService.
The stepup-saml-bundle has been updated to a hotfix that is functionally identical to the current version, the xmlseclibs have been updated and contain mostly [typo fixes](https://github.com/robrichards/xmlseclibs/compare/1.4.1...1.4.2).
This has been tested by hand.
**Related**
SURFnet/Stepup-RA#134
SURFnet/Stepup-Gateway#106
=> SelfService: Update SAML2 dependency

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff
Because the colon is already part of the template, it should not be in the translations:
https://github.com/SURFnet/Stepup-SelfService/blob/81ae4c8b03f03259ff5ca2482f49a2eef1c95060/app/Resources/SurfnetStepupBundle/views/Exception/error404.html.twig#L13
https://github.com/SURFnet/Stepup-SelfService/blob/81ae4c8b03f03259ff5ca2482f49a2eef1c95060/app/Resources/SurfnetStepupBundle/views/Exception/error.html.twig#L13
=> Remove spurious colon from ss.error.text.your_art_code

README.md, app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/config/config.yml, app/config/parameters.yml.dist, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SamlController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/DependencyInjection/Configuration.php, src/Surfnet/StepupSelfService/SelfServiceBundle/DependencyInjection/SurfnetStepupSelfServiceSelfServiceExtension.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/routing.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/translations.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/TestSecondFactor/TestAuthenticationRequestFactory.php
Part of https://www.pivotaltracker.com/story/show/79436876
=> Handle second factor test response

README.md, app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/routing.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig
Part of https://www.pivotaltracker.com/story/show/79436876, will be followed by PR's to implement the test controller action and to handle the authentication response.
=> Add second factor test button

README.md, app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/config/config.yml, app/config/parameters.yml.dist, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SamlController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/DependencyInjection/Configuration.php, src/Surfnet/StepupSelfService/SelfServiceBundle/DependencyInjection/SurfnetStepupSelfServiceSelfServiceExtension.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/routing.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/TestSecondFactor/TestAuthenticationRequestFactory.php
As part of https://www.pivotaltracker.com/story/show/79436876, depends on #118
=> Second factor test action

app/AppKernel.php, app/config/config.yml, app/config/config_dev.yml, app/config/config_test.yml, app/config/parameters.yml.dist, composer.json, composer.lock
These are the changes to the SelfService to lose the SwiftMailer vulnerability. Described in this PivotalTracker ticket [#142301387](https://www.pivotaltracker.com/story/show/142301387).
Note that the solution was to remove the SwiftmailerBundle dependency altogether
=> Vulnerability swiftmailer CVE-2016-10074

src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/public/less/style.less, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/displaySecondFactorTypes.html.twig
Tested in Firefox and Chrome on Linux. On different view port widths.
This pull request fixes the problem when the list of second factors is not ordered in rows from left to right. The second row would start underneath the last item of the first row.
This is a common Bootstrap issue. Bootstrap dictates a row element for each row of columns. This is not always an option. And in that case a css workaround can be used to fix the styling issue.
=> Clear:left after every third column of the second factor selection list

.gitignore, app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/Resources/translations/validators.en_GB.xliff, app/Resources/translations/validators.nl_NL.xliff, app/config/config.yml, app/config/parameters.yml.dist, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SecondFactorController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/DependencyInjection/Configuration.php, src/Surfnet/StepupSelfService/SelfServiceBundle/DependencyInjection/SurfnetStepupSelfServiceSelfServiceExtension.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SecondFactorService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SecondFactorTypeCollection.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/SecondFactorTypeCollectionTest.php
**Review notes**
A user can now register multiple SF tokens. The total amount can be set as a config parameter.
**Tasks**
This PR is part of a series of changes in [SS](https://github.com/OpenConext/Stepup-SelfService/pull/127), [MW](https://github.com/OpenConext/Stepup-Middleware/pull/199) and [GW](https://github.com/OpenConext/Stepup-Gateway/pull/123).
For more information about the changes see [Pivotal](https://www.pivotaltracker.com/story/show/144697285) and the updated [docs](https://github.com/OpenConext/Stepup-Deploy/wiki/API-Design).
=> Support of multiple second factors

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/Resources/translations/validators.en_GB.xliff, app/Resources/translations/validators.nl_NL.xliff, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Controller.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/GssfController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/SmsController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/U2fController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/YubikeyController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Gssf/initiate.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Sms/provePossession.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Sms/sendChallenge.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/U2f/registration.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Yubikey/provePossession.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/displaySecondFactorTypes.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/emailVerificationEmailSent.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/partial/progressBar.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/registrationEmailSent.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/verifyEmail.html.twig
Middleware can skip email verification when configured for an
institution. Selfservice now takes into account that configuration
option and sends the user directly to the last step of the
registration process when possession of the token is proven.
If email verification is enabled, there are four steps shown to the
user:
1. Select token
2. Link token (prove possession)
3. Confirm (verify email)
4. Activate token (vet the token)
If email verification is disabled, the third option is hidden.
=> Allow token registration without email verification

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/Resources/translations/validators.en_GB.xliff, app/Resources/translations/validators.nl_NL.xliff, app/Resources/views/base.html.twig, composer.json, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/routing.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/public/js/registration-print.js, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/public/less/style.less, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/registrationEmailSent.html.twig
The MPDF library is used to render the confirmation page
server-side. This output of the 'email sent' action is used to
generate the PDF. The print stylesheets are used by MPDF to get more
or less the same look and feel as the browser-printed webpage.
In order for the logo to be embedded in the PDF, php-gd is introduced
as a new dependency. If php-gd is not installed, a red cross will
appear on the PDF where the logo should be.
=> Add 'print' and 'pdf' buttons on registration confirm page

src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php
The Mpdf default is to write temporary files to '../../tmp', which in
our case is not a suitable directory. We explicitly tell Mpdf to use
the sys_get_temp_dir folder, which will use the system
default (depending on production setup, probably a private tmp dir for
php-fpm).
=> Use the system temp directory for Mpdf temporary storage

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, composer.json, composer.lock, src/Surfnet/StepupSelfService/SamlStepupProviderBundle/DependencyInjection/Compiler/ViewConfigCollectionPass.php, src/Surfnet/StepupSelfService/SamlStepupProviderBundle/DependencyInjection/SurfnetStepupSelfServiceSamlStepupProviderExtension.php, src/Surfnet/StepupSelfService/SamlStepupProviderBundle/Provider/ViewConfig.php, src/Surfnet/StepupSelfService/SamlStepupProviderBundle/SurfnetStepupSelfServiceSamlStepupProviderBundle.php, src/Surfnet/StepupSelfService/SamlStepupProviderBundle/Tests/Provider/ViewConfigTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/revoke.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/translations.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Twig/Extensions/Extension/SecondFactorType.php
Remove the hard tiqr and biometric references from the translation file and provide a means to translate the token name in the front end.
The solution was based on a very similar problem solved in [RA](https://github.com/OpenConext/Stepup-RA/pull/149).
=> Stop assuming Tiqr is the only GSSP

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig
The add token button was accompanied by a text that did not render
very neatly together. Creating a possibly confusing UI for the end user.
By simplifying the desing, the intent of the button is made much
clearer.
https://www.pivotaltracker.com/story/show/156220699
=> Simplify the 'add token' UI section

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SamlController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/routing.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig
* The test endpoint was changed to no longer test a specified token type.
* To ascertain the user is allowed to use the token test endpoint, a new second factor service method was added. Testing if the user has a vetted LoA >= 2 token.
* The test button is placed in the footer of the vetted tokens table.
Details and a screenshot can be found in:
https://www.pivotaltracker.com/story/show/154476963
=> Show a single token test button

app/config/config.yml
Prevents UnknownUrnExceptions when IDP sends an attribute not defined
in the stepup-saml-bundle. Gateway already does this:
https://github.com/OpenConext/Stepup-Gateway/pull/147/files
=> Ignore unknown attributes in attribute dictionary

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SecondFactorController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/public/less/style.less, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig
The expiration date is only shown on the verified tokens. When the expiration date is met, a label and explanation is added to instruct the user how to restart the registration of his token.
Todo:
=> Show expiration date in the token overview

src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/GssfController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/routing.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/Gssf/initiate.html.twig
The ACS location of GSSP should never show a page without first
redirecting. This way, the user can refresh the page or change the
language before trying again.
See: https://www.pivotaltracker.com/story/show/157843953
=> Redirect after POST when returning from GSSP

src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/SmsController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/YubikeyController.php
The addError construction expects translated messages. The translator
is not available in the controllers and adding extra coupling was
not preferred over changing to flash messages.
See: https://www.pivotaltracker.com/story/show/160228972
=> Use flash messages for error messaging

src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/SmsController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/U2fController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SecondFactorController.php
The feature in Symfony 2 where forms where created by referencing them
by their name (ss_verify_sms_challenge) no longer works in Symfony 3.
This commit fixes this by referencing the form by it's FQDN
(VerifySmsChallengeType).
In the previous Symfony 3.4 compatibility PR, a lot of these fixes have
been done for other Types. This one was overlooked.
See: https://www.pivotaltracker.com/story/show/160473876
=> Prevent form loading issue

.travis.yml, composer.json.travis, composer.lock.travis, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/EntryPointController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SecondFactorController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SecondFactorService.php
The VerifiedSecondFactorSearchQuery now takes the institution as
one of its arguments. This argument is mandatory and is now added
to all the calls of the VerifiedSecondFactorSearch service call.
See https://www.pivotaltracker.com/story/show/160283514
=> Support the amended institution parameter

src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SecondFactorService.php
The VerifiedSecondFactorSearchQuery requires an actor id. The id of the
identity is used for this.
=> Be compatible with recent MW client bundle change

src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SecondFactorService.php
The is a requirement set in the middleware API, used for RA management
related actions. We just pass the users identity id as the actor id.
Which is the correct behavior.
=> Set actor id on the verified second factor query

src/Surfnet/StepupSelfService/SelfServiceBundle/Service/IdentityService.php
The constructor argument was removed from the IdentitySearchQuery as the institution is no longer a required param.
**Relates to**: 
https://github.com/OpenConext/Stepup-Middleware-clientbundle/pull/72
https://github.com/OpenConext/Stepup-Middleware/pull/255
https://github.com/OpenConext/Stepup-RA/pull/183
=> Set institution with setter

src/Surfnet/StepupSelfService/SelfServiceBundle/Service/IdentityService.php
This will fix the art for exceptions when authenticating. The art
was based on the users UUID but should be generated per exception type
and should not be unique per user.
=> Fix art for authentication

app/Resources/views/base.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php
Relative url's weren't supported, because mpdf was trying to get it by
hostname in the request. If however a proxy should update the hostname
it wouldn't work. Therefore the `base` html tag was added which was
supported by mpdf for resolving absolute urls. Also the
logging was added and decent symfony shutdown.
=> Fix mpdf relative url's and logging

composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SecondFactorService.php
The authorization context that was added for the RA application applies
an authorization context to the query. This filters out results that not
match the context of the current RA state (the institution that is
currently active).
For Self Service we do not want to apply that context based filtering.
See: https://www.pivotaltracker.com/story/show/165740432
See: https://github.com/OpenConext/Stepup-Middleware/pull/279
See: https://github.com/OpenConext/Stepup-Middleware-clientbundle/pull/82
=> Find verified second factors without authorization context

composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/EntryPointController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SecondFactorController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SecondFactorService.php
The actorInstitution was removed. this is possible because the SRAA (institution) switcher is removed as it is no longer useful after the FGA changes. This because earlier all overviews where from the viewpoint of an institution but now it's from a registration authority. 
These changes are needed to reflect the changes in RA and Middleware.
=> Remove the actorInstitution

.travis.yml, CHANGELOG.md, composer.lock
This change will apply the countermeasures to harden against CVE 2019-3465 and will effectively bump `robrichards/xmlseclibs` to version 3.0.4
Targetted at release 17 (3.0.1)
=> Upgrade Stepup-saml-bundle to version 4.1.8

src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/ExceptionController.php
Exceptions thrown while not logged in are wrapped in a HttpException.
This is preventing the rendering of a sane error message for the enduser.
https://www.pivotaltracker.com/story/show/170487625
=> Fix exception controller authentication exceptions

app/Resources/views/dev/mock-acs.html.twig, app/config/remote_vetting.yml, app/phpunit.xml.dist, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RemoteVettingController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Mock/RemoteVetting/MockRemoteVetController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/SamlCalloutHelper.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVettingService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Mock/RemoteVetting/MockRemoteVetControllerTest.php
Disable garbage collection for acceptance test
For the acceptance tests the garbage collection is disabled in
order to prevent a segfaults in Travis. This should be fixed in php 7.
See: https://bugs.php.net/bug.php?id=72286
=> Fix RV acceptance tests in Travis

src/Surfnet/StepupSelfService/SelfServiceBundle/Command/RemoteVetValidationCommand.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/RemoteVetAssertionMatchType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeMatch.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeMatchCollection.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVettingService.php
The attrbute matches needed to be mapped with DI.
This is done with the help of a datamapper.
Please review #187 first.
Be aware that the base branch has to be changed before merging.
=> Add data mapper for form attribute matches

app/config/remote_vetting.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RemoteVettingController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/RemoteVetAssertionMatchType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/RemoteVetValidationType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Form/fields.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/AttributeMapper.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Dto/AttributeListDto.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Dto/RemoteVettingProcessDto.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/IdentityProviderFactory.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/RemoteVettingContext.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/SamlCalloutHelper.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/State/AbstractRemoteVettingState.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/State/RemoteVettingState.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/State/RemoteVettingStateInitialised.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeCollection.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeMatch.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeMatchCollection.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVettingService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Mock/RemoteVetting/MockRemoteVetControllerTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/AttributeMapperTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Dto/RemoteVettingProcessDtoTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/RemoteVettingContextTest.php
Add mapper to map local and external (remote vetting) attributes so they can be used to match values on. Currently, only a form is filled in order to select valid attributes.
https://www.pivotaltracker.com/story/show/171571478
=> Add attribute mapping config

app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, app/Resources/translations/validators.en_GB.xliff, app/Resources/translations/validators.nl_NL.xliff, src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/RemoteVetAssertionMatchType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/RemoteVetValidationType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/translations.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/AttributeMapper.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/SamlCalloutHelper.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Mock/RemoteVetting/MockRemoteVetControllerTest.php
The translations for remote vetting needed a bit more
TLC. This was postponed during initial development.
This needs to be merged back after: https://github.com/OpenConext/Stepup-SelfService/pull/192
The first commit is from #192
=> Add missing remote vetting translations

src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Mock/RemoteVetting/MockRemoteVetControllerTest.php
The used locale for development is en_GB. Therefore
some test needed to use en_GB. This will also allow
easier contributions for non native dutch speakers.
=> Use en_GB as E2E test locale

app/config/services_dev.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RemoteVettingController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/RemoteVetAssertionMatchType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Dto/AttributeListDto.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/Attribute.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeMatch.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/AttributeMapperTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Dto/AttributeListDtoTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Dto/RemoteVettingProcessDtoTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Encryption/IdentityEncrypterIntegrationTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Encryption/IdentityEncrypterTest.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Value/AttributeCollectionInterfaceIntegrationTest.php
Multi value attributes should be allowed in order to be
able to handle external SAML IdP's. According to the SAML
spec this should be allowed.
https://www.pivotaltracker.com/story/show/171571414
=>  Allow multi value attributes

app/config/remote_vetting.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RemoteVettingController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/State/RemoteVettingStateDone.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeCollectionAggregate.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVetting/Value/AttributeCollectionInterface.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/RemoteVettingService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/RemoteVetting/Value/AttributeCollectionInterfaceIntegrationTest.php
Move the aggregation of the IdentityData to the RemoteVettingService.
That way the controller will keep lightweight and the responsibility
of remote vetting is delegated and only glue is used in the
controller. This resulted in less coupling.
Also the ProviderName is set in the IdentityData, this needed to be
done after the feature was implemented on a different branch.
=> Move IdentityAggregation to Remote vetting service

app/config/remote_vetting.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RemoteVettingController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/SecondFactor/list.html.twig
Only non expired tokens could be remote vetted. This wasn't fixed
earlier because it came in handy during development.
https://www.pivotaltracker.com/story/show/171571641
https://www.pivotaltracker.com/story/show/171571556
Please review #199 first
=> Prevent remote vetting of expired tokens

.travis.yml
Instead of the version pin, the `--1` flag can be used to fetch the latest version 1 of Composer
=> Use the latest Composer 1 on Travis

src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/registration/gssf/initiate.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/registration/partial/generic_second_factor.html.twig
This will enable SURF to enrich the description used in emails with
links etc.
See: https://www.pivotaltracker.com/story/show/174901359
=> Allow HTML in explanation/description

.gitignore, composer.json, composer.lock, config/packages/security_checker.yaml, symfony.lock
The security checker needs to be updated in favour of a binary version
because the Sensiolabs PHP version is deprecated.
=> Upgrade security checker with binary version

src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RemoteVettingController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/translations.twig, translations/messages.en_GB.xliff, translations/messages.nl_NL.xliff
When during a callout to the remote IdP the session data was expired an
exception was thrown. Now this exception is caught, a flash message is
shown and the enduser gets redirected to the overview page. So the
enduser would be able to try again.
=> Catch RV missing context exception

.travis.yml, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RecoveryTokenController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RecoveryTokenControllerTrait.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SamlController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SelfAssertedTokensController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/routing.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/translations.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfAssertedTokens/AuthenticationRequestFactory.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfAssertedTokens/Dto/ReturnTo.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfAssertedTokens/RecoveryTokenService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfAssertedTokens/RecoveryTokenState.php, translations/messages.en_GB.xliff, translations/messages.nl_NL.xliff, translations/validators.en_GB.xliff, translations/validators.nl_NL.xliff
1. In preparation, the SAT controller was cleaned up by segregating the dedicated RT actions from the registration related actions
2. The 'test' authentication consume assertion endpoint was re-re-used to also serve self-asserted recovery token step up authentications. I considered creating a new SFO SP for this. But that would get complex really soon. The step up bundle does not support multiple ACS locations either. So this solution seemed to fit best.
=> Require step up authentication for Recovery Token create and delete actions

.travis.yml, composer.json, composer.lock, config/legacy/parameters.yaml.dist, config/packages/surfnet_stepup.yaml, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SamlController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SelfVetController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfVetMarshaller.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/SelfVetMarshallerTest.php, symfony.lock
This PR integrates the recent Stepup-Bundle changes where the SecondFactorTypeService is now used to determine the correct LoA. In order to get this job done, the Vetting Type is now passed to the service methods. 
In addition to this, I also updated some CI config. 
See: https://www.pivotaltracker.com/story/show/181933334
See: https://github.com/OpenConext/Stepup-Gateway/pull/258
=> Support the new loa-self-asserted level of assurance

.travis.yml, composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SecondFactorController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/registration/display_vetting_types.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/AuthorizationService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/VettingTypeService.php, translations/messages.en_GB.xliff, translations/messages.nl_NL.xliff, translations/validators.en_GB.xliff, translations/validators.nl_NL.xliff
If available, show the translated vetting type hint for the institution of the identity logged in to the self service.
The message is displayed on the choose vetting type page (if available). If only one vetting type is present. For example, when only desk vetting is possible. The text is not displayed.
[f8f3dd1](https://github.com/OpenConext/Stepup-SelfService/pull/268/commits/f8f3dd16869f984362a9b096753258e60b831992) was added during acceptance testing of the new feature. It stood out that a user with a token vetted on premise, still was allowed to add recovery tokens. And that should not be the case!
/boyscout
=> Display the Institutional vetting type hint

package.json, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RecoveryTokenController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SelfAssertedTokensController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfAssertedTokens/RecoveryTokenState.php, yarn.lock
A recovery token can always be revoked, no step up authentication is required to do so.
The change to `SelfAssertedTokensController` is a boyscout rule fixup. The stepup bundle service was used directly, where use of the SelfService service was required. This was caused by a merge-conflict some time ago..
See: https://www.pivotaltracker.com/story/show/182842669
=> Allow RT revocation without SF token possession

composer.lock, config/legacy/parameters.yaml.dist, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SecondFactorController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/registration/partial/crud_list.html.twig, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfAssertedTokens/Exception/RecoveryTokenConfigurationException.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfAssertedTokens/RecoveryTokenConfig.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfAssertedTokens/RecoveryTokenService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/SelfAssertedTokens/RecoveryTokenConfigTest.php
SMS or safe store recovery token types can be enabled and disabled. But never can both be disabled.
See https://www.pivotaltracker.com/story/show/183636781
=> Add toggles to disable recovery token types

src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/GssfController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/SmsController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/YubikeyController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php, yarn.lock
The activation and mail verification messages where mixed up in the SelfService. Resulting in an error where an unverified token was used to send an activation message to. Resulting in a 500 error.
This behavior was originally posted on slack, but landed in:
See: https://www.pivotaltracker.com/story/show/184159568
=> Do not send activation mail when verify email required

composer.lock, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SelfVetController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/AuthorizationService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SecondFactorService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SelfVetMarshaller.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/SelfVetMarshallerTest.php
For details read the story: https://www.pivotaltracker.com/story/show/184292087
For the MW accompanying this change see: https://github.com/OpenConext/Stepup-Middleware/pull/401
=> Support self-vetting using a self-asserted token

src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/Registration/SmsController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/routing.yml
The ss_registration_sms_prove_possession might have been skipped by the
SMS RT proof op posession where it was removed. During that action this
route was also removed. But it was still used in the token registration
of an SMS token.
The other commit states that: When the max attempts are expired, the view vars did not include the
verifyEmail property. That was fixed in this boy scout commit.
See: https://www.pivotaltracker.com/story/show/184750138
=> SMS prove possession route not found

src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/AuthenticateSafeStoreType.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/VerifySmsChallengeType.php
This was done for the safe-store recovery token authentication form and the verify sms challenge forms.
See: https://www.pivotaltracker.com/story/show/185006156
=> Add autocompte="off" to secret input fields

src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/registration/partial/crud_list.html.twig
When the user is in possession of a vetted token and a recovery token, then display the RT text and add RT button (if one is available for addition)
=> Only show RT button and text when appropriate

src/Surfnet/StepupSelfService/SelfServiceBundle/Form/Type/SendSmsChallengeType.php
This presents the correct keyboard on mobile.
=> Make phone number input type="tel"

src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/registration/partial/generic_second_factor.html.twig
OWASP core ruleset will complain about this, because the use of `text/plain` in conjunction with `method=post` is effectively useless (form values will never become available in the $_POST global).
The form functions just fine without it.
=> Remove unnecessary enctype from form

src/Surfnet/StepupSelfService/SelfServiceBundle/Exception/MissingRequiredAttributeException.php
In SF 6, the new exception handler does not show the exception message in the exception handler. Rather, these errors are handled at another point (authn listeners).
Also see: https://stackoverflow.com/questions/40174266/not-all-exceptions-catched-within-the-error-handler
=> Ensure display of Authn errors

ci/qa/phpstan-baseline.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/ExceptionController.php
When rendering the custom exception page, we test if the MissingRequiredAttributeException. But it also had to be a HTTP exception. That was never the case (also before #313).
By removing the first part of the statement, the error message is displayed correctly once again.
See: https://github.com/OpenConext/Stepup-SelfService/pull/315
=> Simplify exception logical condition, showing the attribute missing error message once again

CHANGELOG.md, ci/qa/phpstan-baseline.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SamlController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/SelfVet/SelfVetConsumeController.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yaml, src/Surfnet/StepupSelfService/SelfServiceBundle/Service/SecondFactorService.php
The additional SelfVet namespace was not yet reflrected in the route (forward) name.
This was the only occurence where the SelfVetController is called by name. There should not be other wrong calls in the project.
See: https://www.pivotaltracker.com/story/show/187412638
=> Set correct SelfVet ACS route

src/Surfnet/StepupSelfService/SelfServiceBundle/Service/ActivationFlowService.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Service/ActivationFlowServiceTest.php
This change will use the only activation flow that's allowed through the entitlement SAML attribute when no preferred activation flow is set with a query parameter.
This was encountered while enhancing the Behat tests with the ability to add SAML-attributes.
=> Use entitlement when no query parameter is set

src/Surfnet/StepupSelfService/SelfServiceBundle/Security/Authentication/Handler/AuthenticationSuccessHandler.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Security/Authentication/SamlAuthenticator.php, src/Surfnet/StepupSelfService/SelfServiceBundle/Security/Authentication/Session/SessionStorage.php
https://github.com/OpenConext/Stepup-SelfService/issues/440
Also added a test in devconf: https://github.com/OpenConext/OpenConext-devconf/pull/22
=> Redirect to initial uri after successful login
